#cloud-config

runcmd:
  - echo "User data script started. Setting up stack size"
  - sed -i '/# End of file/i * soft nofile 65536' /etc/security/limits.conf
  # using unlimited will break boot.
  - sed -i '/# End of file/i * hard nofile 65536' /etc/security/limits.conf
  # - sed -i '/# End of file/i * soft nproc 4096' /etc/security/limits.conf
  # - sed -i '/# End of file/i * hard nproc 8192' /etc/security/limits.conf
  # - echo 'Done setting up stack size'